node_classification:
  HGBn-acm:
    homo_GNN:
      hidden_dim:
        64

      layers_pre_mp:
        1
      layers_post_mp:
        1
      layers_gnn:
        3
      stage_type:
        stack

      activation:
        relu
      dropout:
        0.5
      has_bn:
        False
      gnn_type:
        gcnconv

      has_l2norm:
        False
      lr:
        0.0005
      weight_decay:
        0.0001
      patience:
        30
      max_epoch:
        300
      mini_batch_flag:
        False

    GCN:
      hidden_dim:
        64
      num_layers:
        2
      dropout:
        0.5
      lr:
        0.0005
      weight_decay:
        0.0001
      patience:
        30
      max_epoch:
        300
      mini_batch_flag:
        False
      activation:
        relu
    GAT:
      hidden_dim:
        64
      num_layers:
        2
      dropout:
        0.5
      slope:
        0.05
      num_heads:
        8
      lr:
        0.0005
      weight_decay:
        0.0001
      patience:
        30
      max_epoch:
        300
      mini_batch_flag:
        False
  HGBn-dblp:
    homo_GNN:
      hidden_dim:
        64
      layers_pre_mp:
        1
      layers_post_mp:
        1
      layers_gnn:
        3
      activation:
        relu
      dropout:
        0.5
      has_l2norm:
        False
      has_bn:
        False
      stage_type:
        skipsum
      gnn_type:
        gcnconv
      lr:
        0.0005
      weight_decay:
        0.0001
      patience:
        30
      max_epoch:
        300
      mini_batch_flag:
        False
    GCN:
      hidden_dim:
        64
      num_layers:
        2
      dropout:
        0.5
      lr:
        0.0005
      weight_decay:
        0.0001
      patience:
        30
      max_epoch:
        300
      mini_batch_flag:
        False
      activation:
        relu
  HGBn-freebase:
    homo_GNN:
      hidden_dim:
        64
      layers_pre_mp:
        1
      layers_post_mp:
        1
      layers_gnn:
        3
      activation:
        relu
      dropout:
        0.5
      has_l2norm:
        True
      has_bn:
        True
      stage_type:
        skipsum
      gnn_type:
        gcnconv
      lr:
        0.0005
      weight_decay:
        0.0001
      patience:
        30
      max_epoch:
        300
      mini_batch_flag:
        False
  HGBn-imdb:
    homo_GNN:
      hidden_dim:
        64
      layers_pre_mp:
        1
      layers_post_mp:
        1
      layers_gnn:
        4
      activation:
        relu
      dropout:
        0.5
      has_l2norm:
        True
      has_bn:
        True
      stage_type:
        skipsum
      gnn_type:
        gcnconv
      lr:
        0.0005
      weight_decay:
        0.0001
      patience:
        30
      max_epoch:
        300
      mini_batch_flag:
        False
link_prediction: